name: flutter_vlc_player
description: A VLC-powered alternative to Flutter's video_player. Supports multiple players on one screen.
version: 7.4.3
homepage: https://github.com/solid-software/flutter_vlc_player/

environment:
  sdk: ">=3.5.1 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: software.solid.fluttervlcplayer
        pluginClass: FlutterVlcPlayerPlugin
      ios:
        pluginClass: FlutterVlcPlayerPlugin

dependencies:
  flutter:
    sdk: flutter

  flutter_vlc_player_platform_interface: ^2.0.3
  meta: ^1.15.0
